version: '3.8'
services:
    web:
        build: .
        ports:
            - "8000:9000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
